# ./docker-compose.yml

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  web:
    image: php:8.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php-app/:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true